/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './index.tsx',
    './App.tsx',
    './components/**/*.{ts,tsx}',
    './pages/**/*.{ts,tsx}',
    './services/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Outfit', 'sans-serif'],
      },
      colors: {
        glass: 'rgba(255, 255, 255, 0.05)',
        glassBorder: 'rgba(255, 255, 255, 0.1)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
        dark: 'rgb(var(--color-dark) / <alpha-value>)',
        card: 'rgb(var(--color-card) / <alpha-value>)',
        slate: {
          50: 'rgb(var(--color-slate-50) / <alpha-value>)',
          100: 'rgb(var(--color-slate-100) / <alpha-value>)',
          200: 'rgb(var(--color-slate-200) / <alpha-value>)',
          300: 'rgb(var(--color-slate-300) / <alpha-value>)',
          400: 'rgb(var(--color-slate-400) / <alpha-value>)',
          500: 'rgb(var(--color-slate-500) / <alpha-value>)',
          600: 'rgb(var(--color-slate-600) / <alpha-value>)',
          700: 'rgb(var(--color-slate-700) / <alpha-value>)',
          800: 'rgb(var(--color-slate-800) / <alpha-value>)',
          900: 'rgb(var(--color-slate-900) / <alpha-value>)',
          950: 'rgb(var(--color-slate-950) / <alpha-value>)',
        },
        indigo: {
          50: 'rgb(var(--color-primary) / 0.08)',
          100: 'rgb(var(--color-primary) / 0.16)',
          200: 'rgb(var(--color-primary) / 0.28)',
          300: 'rgb(var(--color-primary) / 0.6)',
          400: 'rgb(var(--color-primary) / 0.78)',
          500: 'rgb(var(--color-primary) / 0.95)',
          600: 'rgb(var(--color-primary) / 1)',
          700: 'rgb(var(--color-primary) / 1)',
          800: 'rgb(var(--color-primary) / 1)',
          900: 'rgb(var(--color-primary) / 1)',
          950: 'rgb(var(--color-primary) / 1)',
        },
        blue: {
          50: 'rgb(var(--color-primary) / 0.08)',
          100: 'rgb(var(--color-primary) / 0.16)',
          200: 'rgb(var(--color-primary) / 0.28)',
          300: 'rgb(var(--color-primary) / 0.6)',
          400: 'rgb(var(--color-primary) / 0.78)',
          500: 'rgb(var(--color-primary) / 0.95)',
          600: 'rgb(var(--color-primary) / 1)',
          700: 'rgb(var(--color-primary) / 1)',
          800: 'rgb(var(--color-primary) / 1)',
          900: 'rgb(var(--color-primary) / 1)',
          950: 'rgb(var(--color-primary) / 1)',
        },
        purple: {
          50: 'rgb(var(--color-secondary) / 0.08)',
          100: 'rgb(var(--color-secondary) / 0.16)',
          200: 'rgb(var(--color-secondary) / 0.28)',
          300: 'rgb(var(--color-secondary) / 0.6)',
          400: 'rgb(var(--color-secondary) / 0.78)',
          500: 'rgb(var(--color-secondary) / 0.95)',
          600: 'rgb(var(--color-secondary) / 1)',
          700: 'rgb(var(--color-secondary) / 1)',
          800: 'rgb(var(--color-secondary) / 1)',
          900: 'rgb(var(--color-secondary) / 1)',
          950: 'rgb(var(--color-secondary) / 1)',
        },
        violet: {
          50: 'rgb(var(--color-secondary) / 0.08)',
          100: 'rgb(var(--color-secondary) / 0.16)',
          200: 'rgb(var(--color-secondary) / 0.28)',
          300: 'rgb(var(--color-secondary) / 0.6)',
          400: 'rgb(var(--color-secondary) / 0.78)',
          500: 'rgb(var(--color-secondary) / 0.95)',
          600: 'rgb(var(--color-secondary) / 1)',
          700: 'rgb(var(--color-secondary) / 1)',
          800: 'rgb(var(--color-secondary) / 1)',
          900: 'rgb(var(--color-secondary) / 1)',
          950: 'rgb(var(--color-secondary) / 1)',
        },
        fuchsia: {
          50: 'rgb(var(--color-secondary) / 0.08)',
          100: 'rgb(var(--color-secondary) / 0.16)',
          200: 'rgb(var(--color-secondary) / 0.28)',
          300: 'rgb(var(--color-secondary) / 0.6)',
          400: 'rgb(var(--color-secondary) / 0.78)',
          500: 'rgb(var(--color-secondary) / 0.95)',
          600: 'rgb(var(--color-secondary) / 1)',
          700: 'rgb(var(--color-secondary) / 1)',
          800: 'rgb(var(--color-secondary) / 1)',
          900: 'rgb(var(--color-secondary) / 1)',
          950: 'rgb(var(--color-secondary) / 1)',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        progress: 'progress 6s linear',
        'scanline': 'scanline 2s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        progress: {
          '0%': { width: '100%' },
          '100%': { width: '0%' },
        },
        scanline: {
          '0%': { backgroundPosition: '0 0' },
          '100%': { backgroundPosition: '0 100%' },
        },
      },
    },
  },
  plugins: [],
};
